apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-hello-np
  labels:
    app: deployment-nodeport
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-nodeport
  template:
    metadata:
      labels:
        app: hello-nodeport
    spec:
      containers:
        - name: hello-app
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "200m"
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: service-hello-np
spec:
  type: NodePort
  selector:
    app: hello-nodeport
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007