apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-hello-clusterip
  labels:
    app: deployment-clusterip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-clusterip
  template:
    metadata:
      labels:
        app: hello-clusterip
    spec:
      containers:
        - name: hello-app
          image: gcr.io/google-samples/hello-app:2.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "200m"
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: hello-clusterip
  ports:
    - port: 80
      targetPort: 8080